# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Explore. Dream. Discover.
email: amitmanchanda1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interested in everything. Passion yet to be found.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amitmanchanda.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  amitmanchanda1995

# Build settings
markdown: kramdown
